apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eshop
  namespace: argocd
spec:
  project: default
  destination:
    namespace: eshop
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: od-artefacts/63f7008119a69d76c5863a22/appBlueprints/eshop/v1
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true