kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-hello-world
  namespace: eshop
  labels:
    name: nginx-hello-world
  annotations:
    omnideqname: eshop(app)->eshop(blueprint)->nginx-hello-world(dep)
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-hello-world
  template:
    metadata:
      labels:
        app: nginx-hello-world
      annotations: {}
    spec:
      containers:
        - name: docker-nginx-hello-world
          image: dockerbogo/docker-nginx-hello-world:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom: []
          volumeMounts: []
      volumes: []
      hostAliases: []
      imagePullSecrets: []
      nodeSelector:
        kubernetes.io/os: linux
      terminationGracePeriodSeconds: 30
