apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eshop
  namespace: argocd
spec:
  project: default
  destination:
    namespace: eks-blueprints
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: apps/eshop
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true