apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eshop
  namespace: argocd
spec:
  project: default
  destination:
    namespace: vk-test
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: od-artefacts/641d864b41e49a551657c81c/appBlueprints/eshop/v1
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true